import { PlusIcon } from '@radix-ui/react-icons'
import {
  ArrowDown,
  Check,
  ChevronDown,
  ChevronUp,
  Download,
  Edit,
  HammerIcon,
  Moon,
  RefreshCw,
  Save,
  SendIcon,
  Sun,
  Trash,
  X
} from 'lucide-react'
import {
  AgentIcon,
  AgnoIcon,
  AgnoTag,
  AnthropicLogo,
  AwsLogo,
  AzureLogo,
  CohereLogo,
  DeepseekLogo,
  FireworksLogo,
  GeminiLogo,
  GroqLogo,
  MistralLogo,
  NextjsTag,
  OllamaLogo,
  OpenAILogo,
  ReasoningIcon,
  ReferencesIcon,
  ShadcnTag,
  SheetIcon,
  TailwindTag,
  UserIcon,
  XaiLogo
} from './custom-icons'
import type { IconTypeMap } from './types'

export const ICONS: IconTypeMap = {
  'open-ai': OpenAILogo,
  mistral: MistralLogo,
  gemini: GeminiLogo,
  aws: AwsLogo,
  azure: AzureLogo,
  anthropic: AnthropicLogo,
  groq: GroqLogo,
  fireworks: FireworksLogo,
  deepseek: DeepseekLogo,
  cohere: CohereLogo,
  ollama: OllamaLogo,
  xai: XaiLogo,
  agno: AgnoIcon,
  user: UserIcon,
  agent: AgentIcon,
  sheet: SheetIcon,
  nextjs: NextjsTag,
  shadcn: ShadcnTag,
  tailwind: TailwindTag,
  reasoning: ReasoningIcon,
  'agno-tag': AgnoTag,
  refresh: RefreshCw,
  edit: Edit,
  save: Save,
  x: X,
  'arrow-down': ArrowDown,
  send: SendIcon,
  download: Download,
  hammer: HammerIcon,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'plus-icon': PlusIcon,
  references: ReferencesIcon,
  trash: Trash,
  sun: Sun,
  moon: Moon
}
